"""Type stubs for the package: everything the extension module defines."""

from ._arris import (
    ArrisError as ArrisError,
    Body as Body,
    BodyDecodeError as BodyDecodeError,
    BodyEncodeError as BodyEncodeError,
    BodyError as BodyError,
    BodyMagicError as BodyMagicError,
    BodyPrecisionError as BodyPrecisionError,
    BodyRejectedError as BodyRejectedError,
    BodyVersionError as BodyVersionError,
    Cancel as Cancel,
    Edge as Edge,
    EulerLine as EulerLine,
    Face as Face,
    FitDegenerateError as FitDegenerateError,
    FitDivergedError as FitDivergedError,
    FitError as FitError,
    FitInvalidToleranceError as FitInvalidToleranceError,
    FitNonFiniteError as FitNonFiniteError,
    ForeignHandleError as ForeignHandleError,
    Frame as Frame,
    GeomAmbiguousError as GeomAmbiguousError,
    GeomAmbiguousUvError as GeomAmbiguousUvError,
    GeomDegenerateError as GeomDegenerateError,
    GeomDegenerateSectionError as GeomDegenerateSectionError,
    GeomError as GeomError,
    GeomInvalidToleranceError as GeomInvalidToleranceError,
    GeomNotOnSurfaceError as GeomNotOnSurfaceError,
    GeomThroughSingularityError as GeomThroughSingularityError,
    GeomUnsupportedError as GeomUnsupportedError,
    Imported as Imported,
    Interrupted as Interrupted,
    Loop as Loop,
    MassProperties as MassProperties,
    Mesh as Mesh,
    MeshChordError as MeshChordError,
    MeshCornersError as MeshCornersError,
    MeshError as MeshError,
    MeshFaceError as MeshFaceError,
    MeshGridTooLargeError as MeshGridTooLargeError,
    MeshIndexOutOfRangeError as MeshIndexOutOfRangeError,
    MeshInternalError as MeshInternalError,
    MeshInvalidInputError as MeshInvalidInputError,
    MeshNonFinitePositionError as MeshNonFinitePositionError,
    MeshNotInBodyError as MeshNotInBodyError,
    MeshRangeOutOfBoundsError as MeshRangeOutOfBoundsError,
    MeshTooManyTrianglesError as MeshTooManyTrianglesError,
    MeshWeldMismatchError as MeshWeldMismatchError,
    Model as Model,
    ModelPoisonedError as ModelPoisonedError,
    NativeDecodeError as NativeDecodeError,
    NativeEncodeError as NativeEncodeError,
    NativeError as NativeError,
    NativeVersionError as NativeVersionError,
    Occurrence as Occurrence,
    OpDegenerateError as OpDegenerateError,
    OpError as OpError,
    OpInternalError as OpInternalError,
    OpInvalidInputError as OpInvalidInputError,
    OpProfileError as OpProfileError,
    OpRejectedError as OpRejectedError,
    OpToleranceError as OpToleranceError,
    OpUnkeyedError as OpUnkeyedError,
    OpUnsupportedError as OpUnsupportedError,
    Profile as Profile,
    Provenance as Provenance,
    Refusal as Refusal,
    Report as Report,
    Role as Role,
    Segment as Segment,
    Shell as Shell,
    StaleHandleError as StaleHandleError,
    StepError as StepError,
    StepLumpsError as StepLumpsError,
    StepNoBodiesError as StepNoBodiesError,
    StepNonFiniteError as StepNonFiniteError,
    StepParseError as StepParseError,
    StepRead as StepRead,
    StepSolid as StepSolid,
    StepTreeError as StepTreeError,
    StepUnsupportedError as StepUnsupportedError,
    TopoError as TopoError,
    TopoPrecisionError as TopoPrecisionError,
    UncheckedRow as UncheckedRow,
    Vertex as Vertex,
    Violation as Violation,
    obj as obj,
    stl_ascii as stl_ascii,
    stl_binary as stl_binary,
    weld as weld,
    __version__ as __version__,
)

__all__ = [
    "ArrisError",
    "Body",
    "BodyDecodeError",
    "BodyEncodeError",
    "BodyError",
    "BodyMagicError",
    "BodyPrecisionError",
    "BodyRejectedError",
    "BodyVersionError",
    "Cancel",
    "Edge",
    "EulerLine",
    "Face",
    "FitDegenerateError",
    "FitDivergedError",
    "FitError",
    "FitInvalidToleranceError",
    "FitNonFiniteError",
    "ForeignHandleError",
    "Frame",
    "GeomAmbiguousError",
    "GeomAmbiguousUvError",
    "GeomDegenerateError",
    "GeomDegenerateSectionError",
    "GeomError",
    "GeomInvalidToleranceError",
    "GeomNotOnSurfaceError",
    "GeomThroughSingularityError",
    "GeomUnsupportedError",
    "Imported",
    "Interrupted",
    "Loop",
    "MassProperties",
    "Mesh",
    "MeshChordError",
    "MeshCornersError",
    "MeshError",
    "MeshFaceError",
    "MeshGridTooLargeError",
    "MeshIndexOutOfRangeError",
    "MeshInternalError",
    "MeshInvalidInputError",
    "MeshNonFinitePositionError",
    "MeshNotInBodyError",
    "MeshRangeOutOfBoundsError",
    "MeshTooManyTrianglesError",
    "MeshWeldMismatchError",
    "Model",
    "ModelPoisonedError",
    "NativeDecodeError",
    "NativeEncodeError",
    "NativeError",
    "NativeVersionError",
    "Occurrence",
    "OpDegenerateError",
    "OpError",
    "OpInternalError",
    "OpInvalidInputError",
    "OpProfileError",
    "OpRejectedError",
    "OpToleranceError",
    "OpUnkeyedError",
    "OpUnsupportedError",
    "Profile",
    "Provenance",
    "Refusal",
    "Report",
    "Role",
    "Segment",
    "Shell",
    "StaleHandleError",
    "StepError",
    "StepLumpsError",
    "StepNoBodiesError",
    "StepNonFiniteError",
    "StepParseError",
    "StepRead",
    "StepSolid",
    "StepTreeError",
    "StepUnsupportedError",
    "TopoError",
    "TopoPrecisionError",
    "UncheckedRow",
    "Vertex",
    "Violation",
    "obj",
    "stl_ascii",
    "stl_binary",
    "weld",
    "__version__",
]
